[[dev-2026-06]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-06/odin-macos-arm64-dev-06.tar.gz"
hash = "sha256-u10q9EQLo8bPMNlaraaVY32GIshMxvXX9bERx72Stuo="

[[dev-2026-06]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-06/odin-linux-arm64-dev-2026-06.tar.gz"
hash = "sha256-gBtpZBN9tPNR9BIdLnHmnkz3drshSYZBFb9UloED58w="

[[dev-2026-06]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-06/odin-macos-amd64-dev-2026-06.tar.gz"
hash = "sha256-/gW2DVL5ivp5iTDVoRHZ2T0bn3JHbej47rN65YYHo5s="

[[dev-2026-06]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-06/odin-linux-amd64-dev-2026-06.tar.gz"
hash = "sha256-EO7hMPbdfJVS+vePbq/WETVR9+W9NYF7iQ9TsGqOMfA="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-06/odin-macos-arm64-dev-06.tar.gz"
hash = "sha256-u10q9EQLo8bPMNlaraaVY32GIshMxvXX9bERx72Stuo="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-06/odin-linux-arm64-dev-2026-06.tar.gz"
hash = "sha256-gBtpZBN9tPNR9BIdLnHmnkz3drshSYZBFb9UloED58w="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-06/odin-macos-amd64-dev-2026-06.tar.gz"
hash = "sha256-/gW2DVL5ivp5iTDVoRHZ2T0bn3JHbej47rN65YYHo5s="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-06/odin-linux-amd64-dev-2026-06.tar.gz"
hash = "sha256-EO7hMPbdfJVS+vePbq/WETVR9+W9NYF7iQ9TsGqOMfA="

[[dev-2026-05]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-05/odin-macos-arm64-dev-2026-05.tar.gz"
hash = "sha256-1iARDlUjUN9G1IAsaOQU82q/cnT9ufKW+de3fZ521uY="

[[dev-2026-05]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-05/odin-linux-arm64-dev-2026-05.tar.gz"
hash = "sha256-GsAdWYaIptT+W2de5fRYePzQuKjEVV3LMdQyN162YOY="

[[dev-2026-05]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-05/odin-macos-amd64-dev-2026-05.tar.gz"
hash = "sha256-Hs9uWwR8Vu4TBNOeoIO84w9+foEMwqEynUXQwI9dcp0="

[[dev-2026-05]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-05/odin-linux-amd64-dev-2026-05.tar.gz"
hash = "sha256-XaIPQyZN0Yrk3Yy1eYn+Z2rJ+iY3ZSd9gVn/0wCJxq8="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-05/odin-macos-arm64-dev-2026-05.tar.gz"
hash = "sha256-1iARDlUjUN9G1IAsaOQU82q/cnT9ufKW+de3fZ521uY="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-05/odin-linux-arm64-dev-2026-05.tar.gz"
hash = "sha256-GsAdWYaIptT+W2de5fRYePzQuKjEVV3LMdQyN162YOY="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-05/odin-macos-amd64-dev-2026-05.tar.gz"
hash = "sha256-Hs9uWwR8Vu4TBNOeoIO84w9+foEMwqEynUXQwI9dcp0="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-05/odin-linux-amd64-dev-2026-05.tar.gz"
hash = "sha256-XaIPQyZN0Yrk3Yy1eYn+Z2rJ+iY3ZSd9gVn/0wCJxq8="

[[dev-2026-04]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-macos-arm64-dev-2026-04.tar.gz"
hash = "sha256-SfzBJuhP2ypRw0pDsLbxxzWmk8Dre7T2LNy8fACU4vE="

[[dev-2026-04]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-linux-amd64-dev-2026-04.tar.gz"
hash = "sha256-f5o6DfwZmH9dTNb0W2KCUIQcSiaE2EuT17cPQjYpx3E="

[[dev-2026-04]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-linux-arm64-dev-2026-04.tar.gz"
hash = "sha256-cWCH9HHIwEYJtbXEeM5d5OtE0EUzFSxnNIw0H0OVwWs="

[[dev-2026-04]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-macos-amd64-dev-2026-04.tar.gz"
hash = "sha256-RfAD/MtCNkZNX8sw3ountF5rmN3HA/ejBJD9HfJVNpM="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-macos-arm64-dev-2026-04.tar.gz"
hash = "sha256-SfzBJuhP2ypRw0pDsLbxxzWmk8Dre7T2LNy8fACU4vE="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-linux-amd64-dev-2026-04.tar.gz"
hash = "sha256-f5o6DfwZmH9dTNb0W2KCUIQcSiaE2EuT17cPQjYpx3E="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-linux-arm64-dev-2026-04.tar.gz"
hash = "sha256-cWCH9HHIwEYJtbXEeM5d5OtE0EUzFSxnNIw0H0OVwWs="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-macos-amd64-dev-2026-04.tar.gz"
hash = "sha256-RfAD/MtCNkZNX8sw3ountF5rmN3HA/ejBJD9HfJVNpM="

[[dev-2026-03]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-03/odin-macos-arm64-dev-2026-03.tar.gz"
hash = "sha256-c+NFXk1DQ/6Z6s93He6h4prhfqp+728qAga0rIQYMbY="

[[dev-2026-03]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-03/odin-linux-arm64-dev-2026-03.tar.gz"
hash = "sha256-OjkGmkcrgMKHWMgQ7frI+ENka97wfQarGciWY6iQX0w="

[[dev-2026-03]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-03/odin-linux-amd64-dev-2026-03.tar.gz"
hash = "sha256-Z+UjDK6W5HJmsSp45kwHdDmw0uDe4oxulfl6yIhE/mI="

[[dev-2026-03]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-03/odin-macos-amd64-dev-2026-03.tar.gz"
hash = "sha256-kzHnS/wzBTW+HOl2NhQeAYPfy72QL+K5GS8XJLkGda8="

[[dev-2026-02]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-02/odin-linux-arm64-dev-2026-02.tar.gz"
hash = "sha256-xwA1J2MJ+u7OO1mh88MWZuCe+tBBPOD45dFjMdVXvHI="

[[dev-2026-02]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-02/odin-macos-arm64-dev-2026-02.tar.gz"
hash = "sha256-rYw9ZYZ9s4ENYD5JTWNA5iLqfDxd7nHHwD0t7WN6u18="

[[dev-2026-02]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-02/odin-macos-amd64-dev-2026-02.tar.gz"
hash = "sha256-yhbxu0GNvdl6mdDdEcGRH20iZpZi4dsK6SwOXV1IMi8="

[[dev-2026-02]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-02/odin-linux-amd64-dev-2026-02.tar.gz"
hash = "sha256-NdLL8kNuLLZCzWbImjMD7YznFMhgNXabS4vol2z54uM="

[[dev-2026-01]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-macos-arm64-dev-2026-01.tar.gz"
hash = "sha256-5yAdPFy+lsgTDfqhydKi1gKq+h+8QKapYwQHb4Cdn7k="

[[dev-2026-01]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-linux-arm64-dev-2026-01.tar.gz"
hash = "sha256-xq0FJrNTrYcqpYmnSG4Zjt42uJYi0n1JhKSYJiE9Vmo="

[[dev-2026-01]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-linux-amd64-dev-2026-01.tar.gz"
hash = "sha256-Up5GS+6StPdSo9MicYMveQDV0lYrUBJjHdPBs0SQmoM="

[[dev-2026-01]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-macos-amd64-dev-2026-01.tar.gz"
hash = "sha256-Nkz2JkyYs3tJEhJBoPBuByIfyO/aBk3fkv3FKMlbHBc="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-macos-arm64-dev-2026-01.tar.gz"
hash = "sha256-5yAdPFy+lsgTDfqhydKi1gKq+h+8QKapYwQHb4Cdn7k="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-linux-arm64-dev-2026-01.tar.gz"
hash = "sha256-xq0FJrNTrYcqpYmnSG4Zjt42uJYi0n1JhKSYJiE9Vmo="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-linux-amd64-dev-2026-01.tar.gz"
hash = "sha256-Up5GS+6StPdSo9MicYMveQDV0lYrUBJjHdPBs0SQmoM="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-macos-amd64-dev-2026-01.tar.gz"
hash = "sha256-Nkz2JkyYs3tJEhJBoPBuByIfyO/aBk3fkv3FKMlbHBc="

#-| AUTO-GENERATED by generate.nu
#-| Do not attempt to modify this unless it's breaking something
