[[dev-2026-04]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-macos-arm64-dev-2026-04.tar.gz"
hash = "sha256-SfzBJuhP2ypRw0pDsLbxxzWmk8Dre7T2LNy8fACU4vE="

[[dev-2026-04]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-linux-amd64-dev-2026-04.tar.gz"
hash = "sha256-f5o6DfwZmH9dTNb0W2KCUIQcSiaE2EuT17cPQjYpx3E="

[[dev-2026-04]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-linux-arm64-dev-2026-04.tar.gz"
hash = "sha256-cWCH9HHIwEYJtbXEeM5d5OtE0EUzFSxnNIw0H0OVwWs="

[[dev-2026-04]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-macos-amd64-dev-2026-04.tar.gz"
hash = "sha256-RfAD/MtCNkZNX8sw3ountF5rmN3HA/ejBJD9HfJVNpM="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-macos-arm64-dev-2026-04.tar.gz"
hash = "sha256-SfzBJuhP2ypRw0pDsLbxxzWmk8Dre7T2LNy8fACU4vE="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-linux-amd64-dev-2026-04.tar.gz"
hash = "sha256-f5o6DfwZmH9dTNb0W2KCUIQcSiaE2EuT17cPQjYpx3E="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-linux-arm64-dev-2026-04.tar.gz"
hash = "sha256-cWCH9HHIwEYJtbXEeM5d5OtE0EUzFSxnNIw0H0OVwWs="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-04/odin-macos-amd64-dev-2026-04.tar.gz"
hash = "sha256-RfAD/MtCNkZNX8sw3ountF5rmN3HA/ejBJD9HfJVNpM="

[[dev-2026-03]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-03/odin-macos-arm64-dev-2026-03.tar.gz"
hash = "sha256-c+NFXk1DQ/6Z6s93He6h4prhfqp+728qAga0rIQYMbY="

[[dev-2026-03]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-03/odin-linux-arm64-dev-2026-03.tar.gz"
hash = "sha256-OjkGmkcrgMKHWMgQ7frI+ENka97wfQarGciWY6iQX0w="

[[dev-2026-03]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-03/odin-linux-amd64-dev-2026-03.tar.gz"
hash = "sha256-Z+UjDK6W5HJmsSp45kwHdDmw0uDe4oxulfl6yIhE/mI="

[[dev-2026-03]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-03/odin-macos-amd64-dev-2026-03.tar.gz"
hash = "sha256-kzHnS/wzBTW+HOl2NhQeAYPfy72QL+K5GS8XJLkGda8="

[[dev-2026-02]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-02/odin-linux-arm64-dev-2026-02.tar.gz"
hash = "sha256-xwA1J2MJ+u7OO1mh88MWZuCe+tBBPOD45dFjMdVXvHI="

[[dev-2026-02]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-02/odin-macos-arm64-dev-2026-02.tar.gz"
hash = "sha256-rYw9ZYZ9s4ENYD5JTWNA5iLqfDxd7nHHwD0t7WN6u18="

[[dev-2026-02]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-02/odin-macos-amd64-dev-2026-02.tar.gz"
hash = "sha256-yhbxu0GNvdl6mdDdEcGRH20iZpZi4dsK6SwOXV1IMi8="

[[dev-2026-02]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-02/odin-linux-amd64-dev-2026-02.tar.gz"
hash = "sha256-NdLL8kNuLLZCzWbImjMD7YznFMhgNXabS4vol2z54uM="

[[dev-2026-01]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-macos-arm64-dev-2026-01.tar.gz"
hash = "sha256-5yAdPFy+lsgTDfqhydKi1gKq+h+8QKapYwQHb4Cdn7k="

[[dev-2026-01]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-linux-arm64-dev-2026-01.tar.gz"
hash = "sha256-xq0FJrNTrYcqpYmnSG4Zjt42uJYi0n1JhKSYJiE9Vmo="

[[dev-2026-01]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-linux-amd64-dev-2026-01.tar.gz"
hash = "sha256-Up5GS+6StPdSo9MicYMveQDV0lYrUBJjHdPBs0SQmoM="

[[dev-2026-01]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-macos-amd64-dev-2026-01.tar.gz"
hash = "sha256-Nkz2JkyYs3tJEhJBoPBuByIfyO/aBk3fkv3FKMlbHBc="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-macos-arm64-dev-2026-01.tar.gz"
hash = "sha256-5yAdPFy+lsgTDfqhydKi1gKq+h+8QKapYwQHb4Cdn7k="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-linux-arm64-dev-2026-01.tar.gz"
hash = "sha256-xq0FJrNTrYcqpYmnSG4Zjt42uJYi0n1JhKSYJiE9Vmo="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-linux-amd64-dev-2026-01.tar.gz"
hash = "sha256-Up5GS+6StPdSo9MicYMveQDV0lYrUBJjHdPBs0SQmoM="

[[latest]]
url = "https://github.com/odin-lang/Odin/releases/download/dev-2026-01/odin-macos-amd64-dev-2026-01.tar.gz"
hash = "sha256-Nkz2JkyYs3tJEhJBoPBuByIfyO/aBk3fkv3FKMlbHBc="

#-| AUTO-GENERATED by generate.nu
#-| Do not attempt to modify this unless it's breaking something
