[[dev-2026-04]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-04/ols-arm64-unknown-linux-gnu.zip"
hash = "sha256-uU8c9KhQZKe+vxP16+fpbedp+KR1Hi/2PYZPY/Mh+0U="

[[dev-2026-04]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-04/ols-arm64-darwin.zip"
hash = "sha256-KRS7cA4iYGGOD+hXXDXWkcuUjXFjFNp7Ugy3MGh9JvI="

[[dev-2026-04]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-04/ols-x86_64-unknown-linux-gnu.zip"
hash = "sha256-WkIp7zH4cO/KDz7yOqGZtg2Lh7wkzwwPetxWJo41HCo="

[[dev-2026-04]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-04/ols-x86_64-darwin.zip"
hash = "sha256-lRezn9UP/LXB9ElR/RDsuAoBflc2O6QdOZw22VPlzxY="

[[latest]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-04/ols-arm64-unknown-linux-gnu.zip"
hash = "sha256-uU8c9KhQZKe+vxP16+fpbedp+KR1Hi/2PYZPY/Mh+0U="

[[latest]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-04/ols-arm64-darwin.zip"
hash = "sha256-KRS7cA4iYGGOD+hXXDXWkcuUjXFjFNp7Ugy3MGh9JvI="

[[latest]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-04/ols-x86_64-unknown-linux-gnu.zip"
hash = "sha256-WkIp7zH4cO/KDz7yOqGZtg2Lh7wkzwwPetxWJo41HCo="

[[latest]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-04/ols-x86_64-darwin.zip"
hash = "sha256-lRezn9UP/LXB9ElR/RDsuAoBflc2O6QdOZw22VPlzxY="

[[dev-2026-02]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-02/ols-arm64-darwin.zip"
hash = "sha256-JARE8RlbExRgpsXqJ83rsjWEeVtKekjBQsjngcBhrzw="

[[dev-2026-02]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-02/ols-x86_64-darwin.zip"
hash = "sha256-cgHU8MtldnWicS7s98to+KE34J4m3bgoUbcnq8jGJH8="

[[dev-2026-02]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-02/ols-x86_64-unknown-linux-gnu.zip"
hash = "sha256-VeUT+VWt1c7H1u9mx6Y76XRZSeB5qwEAsWn93KTNDH0="

[[dev-2026-02]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-02/ols-arm64-unknown-linux-gnu.zip"
hash = "sha256-aX/o7Yfr76Gla4O6boq4nHIzuJnxBxDKNcKCBZCRHHI="

[[dev-2026-01]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-01/ols-x86_64-unknown-linux-gnu.zip"
hash = "sha256-e9wW2lYu7RxzO8y0TdwwEB1b8Zhd4DnA4NbFPwsoSPQ="

[[dev-2026-01]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-01/ols-x86_64-darwin.zip"
hash = "sha256-cOcUF1iuf6AqmRx8IhEYFEIjqPCE75bSRgaR5S0bC0Y="

[[dev-2026-01]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-01/ols-arm64-unknown-linux-gnu.zip"
hash = "sha256-Tls7Cx1l04E45Cp0t07Z+k/x66ZA1tWrGmNA9qOnU/U="

[[dev-2026-01]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-01/ols-arm64-darwin.zip"
hash = "sha256-Bz3f0uOGbU0RS+ITD1yFI6KSsgAIwHRSOUgnEbEJmRM="

[[dev-2026-03]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-03/ols-arm64-darwin.zip"
hash = "sha256-MiioJjyrAYxtpP6yA/ksKworfp5tZbh8TSG/dH933VE="

[[dev-2026-03]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-03/ols-x86_64-unknown-linux-gnu.zip"
hash = "sha256-5wYzymKEPFYymNXmFJEgg4bU1pCfjcLa7ZusH6X3bD8="

[[dev-2026-03]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-03/ols-x86_64-darwin.zip"
hash = "sha256-zkdVqCsyWLIMB8Wwa9hAK524h/VJljPNAF6TgCMMeOU="

[[dev-2026-03]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-03/ols-arm64-unknown-linux-gnu.zip"
hash = "sha256-Eby4aAcsIdEQ+mnapO4c+1F8GK9XNn6365GbBIg3dyE="

[[latest]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-01/ols-x86_64-unknown-linux-gnu.zip"
hash = "sha256-e9wW2lYu7RxzO8y0TdwwEB1b8Zhd4DnA4NbFPwsoSPQ="

[[latest]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-01/ols-x86_64-darwin.zip"
hash = "sha256-cOcUF1iuf6AqmRx8IhEYFEIjqPCE75bSRgaR5S0bC0Y="

[[latest]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-01/ols-arm64-unknown-linux-gnu.zip"
hash = "sha256-Tls7Cx1l04E45Cp0t07Z+k/x66ZA1tWrGmNA9qOnU/U="

[[latest]]
url = "https://github.com/DanielGavin/ols/releases/download/dev-2026-01/ols-arm64-darwin.zip"
hash = "sha256-Bz3f0uOGbU0RS+ITD1yFI6KSsgAIwHRSOUgnEbEJmRM="

#-| AUTO-GENERATED by generate.nu
#-| Do not attempt to modify this unless it's breaking something
