name: Update manifests

permissions:
  contents: write

on:
  schedule:
    - cron: "0,30 0/4 * * *"
  push:
    paths:
      - "generate.nu"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Setup Lix
        uses: canidae-solutions/lix-quick-install-action@v4
      - name: Setup Nu
        uses: hustcer/setup-nu@v3
      - name: Setup Git credentials
        uses: fregante/setup-git-user@v2

      - name: Update manifests
        run: nu generate.nu

      - name: Push changes
        continue-on-error: true
        run: git commit -am "update manifests"
          git push
